import { useFormContext } from 'react-hook-form';
import type { BriefFormValues } from '../../../lib/schema/campaign-brief';
import type { DerivedCalcs } from '../../../lib/calc/derive';
import { FIELD_INFO } from '../../../lib/planning-copy';
import {
  DateField,
  RadioGroupField,
  SectionCard,
  TextAreaField,
} from '../fields';

export function Section2({ calc }: { calc: DerivedCalcs | null }) {
  const { setValue, getValues } = useFormContext<BriefFormValues>();

  const seedConstraint = () => {
    if (!calc) return;
    const parts: string[] = [];
    if (calc.targets.allowableCac !== null) {
      parts.push(
        `Allowable ${calc.build === 'leadGen' ? 'CPL' : 'CAC'} is $${calc.targets.allowableCac}`,
      );
    }
    if (calc.targets.breakEvenRoas !== null)
      parts.push(`break-even ROAS ${calc.targets.breakEvenRoas}x`);
    if (calc.targets.targetRoas !== null)
      parts.push(`target ROAS ${calc.targets.targetRoas}x`);
    if (calc.ltv.paybackMonthsFractional !== null)
      parts.push(`payback ~${calc.ltv.paybackMonthsFractional} months`);
    const text = parts.length
      ? `Value is created only if ${parts.join(', ')}. (auto-summarised from §1)`
      : '';
    if (!text) return;
    setValue('s2.economicConstraint.text', text, { shouldDirty: true });
    setValue('s2.economicConstraint.autoGeneratedFrom', text);
  };

  const edited =
    getValues('s2.economicConstraint.autoGeneratedFrom') !== null &&
    getValues('s2.economicConstraint.text') !==
      getValues('s2.economicConstraint.autoGeneratedFrom');

  return (
    <SectionCard
      id="s2"
      number="2"
      title="Business Objective & Decision Standard"
      subtitle="The five questions. Answering them badly here is cheaper than answering them badly with spend."
    >
      <TextAreaField
        name="s2.businessOutcome"
        label="1 · What business outcome are we trying to change?"
      />
      <div className="sm:col-span-2">
        <TextAreaField
          name="s2.economicConstraint.text"
          label="2 · What economic constraint determines whether that outcome creates value?"
          help={edited ? 'Edited from the auto-summary.' : undefined}
        />
        <button
          type="button"
          onClick={seedConstraint}
          className="mt-1 text-xs text-neutral-500 underline hover:text-neutral-700"
        >
          insert summary from §1
        </button>
      </div>
      <TextAreaField
        name="s2.signalProximity"
        label="3 · What signal will the platform optimize, and how close is it to the business outcome?"
        help="Links to §4 — the optimization event."
      />
      <TextAreaField
        name="s2.causationEvidence"
        label="4 · What evidence would distinguish causation from attribution or coincidence?"
        help="Links to the experiment plan (slice 2)."
      />
      <TextAreaField
        name="s2.changeOurMind.text"
        label="5 · What would change our mind? (the pre-registration)"
        info={FIELD_INFO.preRegistration}
        placeholder="e.g. If cost per qualified lead stays above $120 for the first 3 weeks at full budget…"
      />
      <DateField name="s2.changeOurMind.decisionDate" label="…and when will we decide?" />

      <RadioGroupField
        name="s2.purpose"
        label="Campaign purpose"
        info={FIELD_INFO.earningLearning}
        help="You cannot get both from the same ad set. Choose one and write it down. §3.7"
        options={[
          {
            value: 'EARNING',
            label: 'EARNING — maximize outcome',
            description: 'No clean read will be available.',
          },
          {
            value: 'LEARNING',
            label: 'LEARNING — run a controlled experiment',
            description: 'Will leave money on the table.',
          },
        ]}
      />
    </SectionCard>
  );
}
