import { z } from 'zod';
import { isoDate } from '../primitives';

/**
 * S2 — Business objective & decision standard: the playbook's five
 * questions plus the EARNING/LEARNING choice (§3.7 — delivery is
 * optimization, not an experiment; you cannot get both from one ad set).
 */
export const s2Schema = z.object({
  businessOutcome: z.string().default(''),
  economicConstraint: z.object({
    text: z.string().default(''),
    /** Snapshot of the auto-summary the text was seeded from; null = edited. */
    autoGeneratedFrom: z.string().nullable(),
  }),
  signalProximity: z.string().default(''),
  causationEvidence: z.string().default(''),
  /** The pre-registration. BLOCKING if empty at submit. */
  changeOurMind: z.object({
    text: z.string().default(''),
    decisionDate: isoDate,
  }),
  purpose: z.enum(['EARNING', 'LEARNING']).nullable(),
});
export type S2Values = z.infer<typeof s2Schema>;

export const emptyS2 = (): S2Values => ({
  businessOutcome: '',
  economicConstraint: { text: '', autoGeneratedFrom: null },
  signalProximity: '',
  causationEvidence: '',
  changeOurMind: { text: '', decisionDate: null },
  purpose: null,
});
